# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24459e0c4025df4aae4955230f3904fc4da4c2fe2a1d177e72ae3bee4d228505b66e7748c07cac52c48cbbafe9335c8778885ec3c44f36d95cb2f482ea8be0c

test:
  secret_key_base: 9148c645ea8818a9805a7a9f1f3bf2d3856a6ab1057c5d4d847bbeed92d53d4b3b2acb406a2ab867104fa840744849049e55b8440e6b2fb6c6c4f2bbe2c2abf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
