version: '3'

services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: mobydock
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - ~/.docker-volumes/mobydock/postgresql/data:/var/lib/postgresql/data
  
  redis:
    image: redis:2.8.22
    ports:
      - '6379:6379'
    volumes:
      - ~/.docker-volumes/mobydock/redis/data:/var/lib/redis/data

  webapp:
    build: .
    links:
      - postgres
      - redis
    volumes:
      .:/opt/app
    ports:
      - '8000:8000'
    env_file:
      - .mobydock.env
