FROM node:alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package.json .

RUN ["yarn", "install"]

COPY . .

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=30s --retries=3 CMD curl -f http://localhost:3000 || exit 1

CMD [ "yarn", "start" ]


